options:
  custom-slurm-repo:
    type: string
    default: ""
    description: >
      Use a custom repository for Slurm installation.

      This can be set to the Organization's local mirror/cache of packages and
      supersedes the Omnivector repositories. Alternatively, it can be used to
      track a `testing` Slurm version, e.g. by setting to
      `ppa:omnivector/osd-testing` (on Ubuntu), or
      `https://omnivector-solutions.github.io/repo/centos7/stable/$basearch`
      (on CentOS).

      Note: The configuration `custom-slurm-repo` must be set *before*
      deploying the units. Changing this value after deploying the units will
      not reinstall Slurm.
  slurmdbd-debug:
    type: string
    default: info
    description: >
      The level of detail to provide slurmdbd daemon's logs. The default value
      is `info`. If the slurmdbd daemon is initiated with `-v` or `--verbose`
      options, that debug level will be preserve or restored upon
      reconfiguration.
