options:
  slurmdbd_debug:
    type: string
    default: info
    description: >-
      "The level of detail to provide slurmdbd daemon's logs. The default value
      is info. If the slurmdbd daemon is initiated with -v or --verbose
      options, that debug level will be preserve or restored upon
      reconfiguration."
  snap-store-channel:
    type: string
    description: snap store channel to install slurm snap from
    default: "stable"
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
