options:
  cluster-name:
    type: string
    default: osd-cluster
    description: >
      Name to be recorded in database for jobs from this cluster.

      This is important if a single database is used to record information from
      multiple Slurm-managed clusters.
  default-partition:
    type: string
    default: ""
    description: >
      Default Slurm partition. This is only used if defined, and must match an
      existing partition.
  custom-config:
    type: string
    default: ""
    description: >
      User supplied Slurm configuration.

      This value supplements the charm supplied `slurm.conf` that is used for
      Slurm Controller and Compute nodes.

      Example usage:
      $ juju config slurmcltd custom-config="FirstJobId=1234"
  proctrack-type:
    type: string
    default: proctrack/cgroup
    description: >
      Identifies the plugin to be used for process tracking on a job step
      basis.
  cgroup-config:
    type: string
    default: |
      CgroupAutomount=yes
      ConstrainCores=yes
    description: >
      Configuration content for `cgroup.conf`.
  health-check-interval:
    default: 600
    type: int
    description: Interval in seconds between executions of the Health Check.
  health-check-state:
    default: "ANY,CYCLE"
    type: string
    description: Only run the Health Check on nodes in this state.
